<?php
	// All supported server classes
  $server_array = array(
	array('name' => '----', 'servers_class' => '1'),
	array('name' => 'Age of Empires II', 'servers_class' => 'ase;aoe2'),
	array('name' => 'Alien vs Predator 2', 'servers_class' => 'gamespy;avp2'),
	array('name' => 'Americans Army', 'servers_class' => 'gamespy2;aa'),
	array('name' => 'Americans Army 3', 'servers_class' => 'gamespy3;aa3'),
	array('name' => 'Alien Arena', 'servers_class' => 'quake2;alienarena'),
	array('name' => 'Armed Assault', 'servers_class' => 'gamespy2;armedassault'),
	array('name' => 'Assault Cube', 'servers_class' => 'cube;assaultcube'),
	array('name' => 'Baldur\'s Gate', 'servers_class' => 'gamespy;baldursgate'),
	array('name' => 'Battlefield', 'servers_class' => 'gamespy;bf'),
	array('name' => 'Battlefield 2', 'servers_class' => 'gamespy3;bf2'),
	array('name' => 'Battlefield 2142', 'servers_class' => 'gamespy3;bf2142'),
	array('name' => 'Battlefield Vietnam', 'servers_class' => 'gamespy2;bfv'),
	array('name' => 'Breed', 'servers_class' => 'gamespy2;breed'),
	array('name' => 'C&amp;C Renegade', 'servers_class' => 'gamespy;ccrenegade'),
	array('name' => 'Call of Duty', 'servers_class' => 'quake3;cod'),
	array('name' => 'Call of Duty - United Offensive', 'servers_class' => 'quake3;coduo'),
	array('name' => 'Call of Duty 2', 'servers_class' => 'quake3;cod2'),
	array('name' => 'Call of Duty 4', 'servers_class' => 'quake3;cod4'),
	array('name' => 'Call of Duty 5: World at War', 'servers_class' => 'quake3;cod5'),
	array('name' => 'Call of Duty: Black Ops', 'servers_class' => 'codbo;codbo'),
	array('name' => 'Call of Juarez', 'servers_class' => 'ase;coj'),
	array('name' => 'Chaser', 'servers_class' => 'ase;chaser'),
	array('name' => 'Chrome', 'servers_class' => 'ase;chrome'),
	array('name' => 'Codename Eagle', 'servers_class' => 'gamespy;codenameeagle'),
	array('name' => 'Commandos 3: Destination Berlin (Unverified)', 'servers_class' => 'gamespy;comandos3'),
	array('name' => 'Contract J.A.C.K', 'servers_class' => 'gamespy;contract'),
	array('name' => 'Cross Racing Championship', 'servers_class' => 'ase;crc'),
	array('name' => 'Counter-Strike (old protocol)', 'servers_class' => 'halflife;csold'),
	array('name' => 'Counter-Strike', 'servers_class' => 'source;cs'),
	array('name' => 'Counter-Strike: Source', 'servers_class' => 'source;css'),
	array('name' => 'Crysis', 'servers_class' => 'gamespy3;crysis'),
	array('name' => 'Crysis Wars', 'servers_class' => 'gamespy3;crysiswars'),
	array('name' => 'Daikatana', 'servers_class' => 'quake2;daikatana'),
	array('name' => 'Day of Defeat', 'servers_class' => 'source;dod'),
	array('name' => 'Day of Defeat: Source', 'servers_class' => 'source;dodsource'),
	array('name' => 'Deadly Dozen: Pacific Theater', 'servers_class' => 'gamespy;ddpt'),
	array('name' => 'Descent 3', 'servers_class' => 'gamespy;descent3'),
	array('name' => 'Deus Ex', 'servers_class' => 'gamespy2;deusex'),
	array('name' => 'Devastation', 'servers_class' => 'ut2003;deva'),
	array('name' => 'Dirt Track Racing II', 'servers_class' => 'gamespy;dtr2'),
	array('name' => 'Doom 3', 'servers_class' => 'doom3;doom3'),
	array('name' => 'Drakan: Order of the Flame', 'servers_class' => 'gamespy;drakan'),
	array('name' => 'Enemy Territory (Wolfenstein)', 'servers_class' => 'quake3;et'),
	array('name' => 'Enemy Territory Quake Wars', 'servers_class' => 'quakewars;etqw'),
	array('name' => 'F1 2002', 'servers_class' => 'gamespy;f12002'),
	array('name' => 'FarCry', 'servers_class' => 'cry;farcry'),
	array('name' => 'Fear', 'servers_class' => 'gamespy2;fear'),
	array('name' => 'Giants: Citizen Kabuto', 'servers_class' => 'gamespy;giants'),
	array('name' => 'Global Operations', 'servers_class' => 'gamespy;globaloperations'),
	array('name' => 'Gore', 'servers_class' => 'gamespy;gore'),
	array('name' => 'Ghost Recon: Advanced Warfighter', 'servers_class' => 'gamespy2;ghostreconaw'),
	array('name' => 'Ghost Recon: Advanced Warfighter 2', 'servers_class' => 'gamespy2;ghostreconaw2'),
	array('name' => 'Half-Life', 'servers_class' => 'source;hl'),
	array('name' => 'Half-Life 2', 'servers_class' => 'source;hl2'),
	array('name' => 'Half-Life (old Protocol)', 'servers_class' => 'halflife;hlold'),
	array('name' => 'Halo: Combat Evolved', 'servers_class' => 'gamespy2;halo'),
	array('name' => 'Halo 2', 'servers_class' => 'gamespy2;halo2'),
	array('name' => 'Heretic 2', 'servers_class' => 'gamespy;heretic2'),
	array('name' => 'Hexen World', 'servers_class' => 'quake2;hexen'),
	array('name' => 'Homeworld 2', 'servers_class' => 'gamespy;homeworld2'),
	array('name' => 'IGI 2', 'servers_class' => 'gamespy;igi2'),
	array('name' => 'IL-2 Sturmovik', 'servers_class' => 'gamespy;il2'),
	array('name' => 'Iron Storm', 'servers_class' => 'gamespy;ironstorm'),
	array('name' => 'James Bond: Nightfire', 'servers_class' => 'gamespy;jb'),
	array('name' => 'Jedi Knight: Jedi Academy / Jedi Knight 2', 'servers_class' => 'quake3;jediacademy'),
	array('name' => 'Kingpin: Life of Crime', 'servers_class' => 'quake2;kingpin'),
	array('name' => 'Killing Floor', 'servers_class' => 'unreal2;killingfloor'),
	array('name' => 'Medal of Honor', 'servers_class' => 'gamespy;mohallied'),
	array('name' => 'Natural Selection', 'servers_class' => 'source;naturalsel'),
	array('name' => 'No One Lives Forever', 'servers_class' => 'gamespy;nolf'),
	array('name' => 'OpenTTD', 'servers_class' => 'openttd;openttd'),
	array('name' => 'Painkiller', 'servers_class' => 'gamespy2;painkiller'),
	array('name' => 'Quake 1 / Quakeworld', 'servers_class' => 'quakeworld;quakeworld'),
	array('name' => 'Quake 2', 'servers_class' => 'quake2;quake2'),
	array('name' => 'Quake 3 Arena', 'servers_class' => 'quake3;quake3a'),
	array('name' => 'Quake 4', 'servers_class' => 'quake3;quake4'),
	array('name' => 'Red Orchestra', 'servers_class' => 'gamespy;redorchestra'),
	array('name' => 'Return to Castle Wolfenstein', 'servers_class' => 'quake3;rtcw'),
	array('name' => 'Rune', 'servers_class' => 'gamespy;rune'),
	array('name' => 'Soldier of Fortune 2', 'servers_class' => 'quake3;sof2'),
  array('name' => 'Star Trek Voyager: Elite Force', 'servers_class' => 'quake3;eliteforce'),
	array('name' => 'SWAT 4', 'servers_class' => 'gamespy;swat4'),
	array('name' => 'TeamSpeak 2', 'servers_class' => 'ts2;ts2', 'encoding' => 'ISO-8859-1'),
	array('name' => 'TeamSpeak 3', 'servers_class' => 'ts3;ts3', 'encoding' => 'UTF-8'),
	array('name' => 'Unreal Tournament', 'servers_class' => 'gamespy;ut'),
	array('name' => 'Unreal Tournament 3', 'servers_class' => 'ut3;ut3'),
	array('name' => 'Unreal Tournament 2003', 'servers_class' => 'unreal2;ut2003'),
	array('name' => 'Unreal Tournament 2004', 'servers_class' => 'unreal2;ut2004', 'encoding' => 'ISO-8859-1'),
	array('name' => 'Warsow', 'servers_class' => 'warsow;warsow')

	//    array('name' => 'Hidden &amp; Dangerous 2', 'servers_class' => 'hd2'),
	//    array('name' => 'S.W.A.T.', 'servers_class' => 'swat'),
  
//    array('name' => '----', 'servers_class' => '1'),
//    array('name' => 'America\'s Army', 'servers_class' => 'aa'),
//    array('name' => 'Armagetronad', 'servers_class' => 'atron'),
//    array('name' => 'Battlefield', 'servers_class' => 'bf'),  
//    array('name' => 'Battlefield 2', 'servers_class' => 'bf2'),  
//    array('name' => 'Battlefield 2142', 'servers_class' => 'bf2142'),  
//    array('name' => 'Battlefield Vietnam', 'servers_class' => 'bfv'),
//    array('name' => 'C&amp;C Renegade', 'servers_class' => 'renegade'),  
//    array('name' => 'Call of Duty', 'servers_class' => 'cod'),  
//    array('name' => 'Call of Duty 2', 'servers_class' => 'cod2'),  
//    array('name' => 'Call of Duty 4', 'servers_class' => 'cod4'),   
//    array('name' => 'Call of Duty 5', 'servers_class' => 'cod5'),    
//    array('name' => 'CounterStrike', 'servers_class' => 'cs'),   
//    array('name' => 'CounterStrike: Source', 'servers_class' => 'css'),   
//    array('name' => 'Day of Defeat: Source', 'servers_class' => 'dods'),   
//    array('name' => 'Doom 3', 'servers_class' => 'd3'),   
//    array('name' => 'Descent 3', 'servers_class' => 'descent3'),   
//    array('name' => 'Descent 3 Gamespy', 'servers_class' => 'des3gs'),
//    array('name' => 'Elite Force', 'servers_class' => 'ef'), 
//    array('name' => 'Enemy Territory', 'servers_class' => 'et'),   
//    array('name' => 'Enemy Territory: Quake Wars', 'servers_class' => 'etqw'), 
//    array('name' => 'Fear', 'servers_class' => 'fear'),
//    array('name' => 'Halo', 'servers_class' => 'halo'),   
//    array('name' => 'Hidden &amp; Dangerous 2', 'servers_class' => 'hd2'),
//    array('name' => 'Half-Life &amp; Mods / Half-Life 2', 'servers_class' => 'hl'),
//    array('name' => 'Half-Life Old', 'servers_class' => 'hl_old'),
//    array('name' => 'Jedi Knight: Jedi Academy / Jedi Knight 2', 'servers_class' => 'jedi'),  
//    array('name' => 'Left 4 Dead', 'servers_class' => 'l4d'),   
//    array('name' => 'Medal of Honor', 'servers_class' => 'mohaa'),
//    array('name' => 'No One Lives Forever', 'servers_class' => 'nolf'),
//    array('name' => 'Painkiller', 'servers_class' => 'pk'),
//    array('name' => 'Quake 1 / Quakeworld', 'servers_class' => 'q1'),
//    array('name' => 'Quake 2', 'servers_class' => 'q2'),
//    array('name' => 'Quake 3 Arena', 'servers_class' => 'q3a'),  
//    array('name' => 'Quake 4', 'servers_class' => 'q4'),
//    array('name' => 'Return to Castle Wolfenstein', 'servers_class' => 'rtcw'),  
//    array('name' => 'Rune', 'servers_class' => 'rune'),
//    array('name' => 'Shockvoice', 'servers_class' => 'shockvoice'),
//    array('name' => 'Soldier of Fortune 2', 'servers_class' => 'sof2'),
//    array('name' => 'S.W.A.T.', 'servers_class' => 'swat'),
//    array('name' => 'Tactical Ops: Assault on Terror', 'servers_class' => 'toaot'),   
//    array('name' => 'Tactical Ops: Crossfire', 'servers_class' => 'toc'),   
//    array('name' => 'Team Fortress 2', 'servers_class' => 'tf2'),   
//    array('name' => 'TeamSpeak 2', 'servers_class' => 'ts'),
//    array('name' => 'TeamSpeak 3', 'servers_class' => 'ts3'),
//    array('name' => 'TrackMania Nations: Forever', 'servers_class' => 'tmnf'),
//    array('name' => 'Unreal Tournament', 'servers_class' => 'ut'),
//    array('name' => 'Unreal Tournament 2003 &amp; 2004 / Red Orchestra', 'servers_class' => 'ut2004'),  
//    array('name' => 'Unreal Tournament 3', 'servers_class' => 'ut3'),      
//    array('name' => 'Warsow', 'servers_class' => 'warsow')
  );
?>
