CREATE TABLE {pre}_replays_sc2 (
  replays_sc2_id {serial},
  replays_id int(8) NOT NULL default '0',
  replays_sc2_date int(14) NOT NULL default '0',
  replays_sc2_s2type varchar(4) NOT NULL default '',
  replays_sc2_version varchar(20) NOT NULL default '',
  replays_sc2_build varchar(20) NOT NULL default '',
  replays_sc2_length int(8) NOT NULL default '0',
  replays_sc2_gametype varchar(20) NOT NULL default '',
  replays_sc2_mode varchar(20) NOT NULL default '',
  replays_sc2_mapname varchar(80) NOT NULL default '',
  replays_sc2_maphash varchar(80) NOT NULL default '',
  replays_sc2_gateway varchar(12) NOT NULL default '',
  replays_sc2_winner int(2) NOT NULL default 0,
	replays_sc2_observers mediumblob NOT NULL,
  replays_sc2_slot01_name varchar(25) NOT NULL default '',
  replays_sc2_slot01_race char(2) NOT NULL default '',
  replays_sc2_slot01_details mediumblob NOT NULL,
  replays_sc2_slot01_advanced_details mediumblob NOT NULL,
  replays_sc2_slot02_name varchar(25) NOT NULL default '',
  replays_sc2_slot02_race char(2) NOT NULL default '',
  replays_sc2_slot02_details mediumblob NOT NULL,
  replays_sc2_slot02_advanced_details mediumblob NOT NULL,
  replays_sc2_slot03_name varchar(25) NOT NULL default '',
  replays_sc2_slot03_race char(2) NOT NULL default '',
  replays_sc2_slot03_details mediumblob NOT NULL,
  replays_sc2_slot03_advanced_details mediumblob NOT NULL,
  replays_sc2_slot04_name varchar(25) NOT NULL default '',
  replays_sc2_slot04_race char(2) NOT NULL default '',
  replays_sc2_slot04_details mediumblob NOT NULL,
  replays_sc2_slot04_advanced_details mediumblob NOT NULL,
  replays_sc2_slot05_name varchar(25) NOT NULL default '',
  replays_sc2_slot05_race char(2) NOT NULL default '',
  replays_sc2_slot05_details mediumblob NOT NULL,
  replays_sc2_slot05_advanced_details mediumblob NOT NULL,
  replays_sc2_slot06_name varchar(25) NOT NULL default '',
  replays_sc2_slot06_race char(2) NOT NULL default '',
  replays_sc2_slot06_details mediumblob NOT NULL,
  replays_sc2_slot06_advanced_details mediumblob NOT NULL,
  replays_sc2_slot07_name varchar(25) NOT NULL default '',
  replays_sc2_slot07_race char(2) NOT NULL default '',
  replays_sc2_slot07_details mediumblob NOT NULL,
  replays_sc2_slot07_advanced_details mediumblob NOT NULL,
  replays_sc2_slot08_name varchar(25) NOT NULL default '',
  replays_sc2_slot08_race char(2) NOT NULL default '',
  replays_sc2_slot08_details mediumblob NOT NULL,
  replays_sc2_slot08_advanced_details mediumblob NOT NULL,
  replays_sc2_slot09_name varchar(25) NOT NULL default '',
  replays_sc2_slot09_race char(2) NOT NULL default '',
  replays_sc2_slot09_details mediumblob NOT NULL,
  replays_sc2_slot09_advanced_details mediumblob NOT NULL,
  replays_sc2_slot10_name varchar(25) NOT NULL default '',
  replays_sc2_slot10_race char(2) NOT NULL default '',
  replays_sc2_slot10_details mediumblob NOT NULL,
  replays_sc2_slot10_advanced_details mediumblob NOT NULL,
  replays_sc2_slot11_name varchar(25) NOT NULL default '',
  replays_sc2_slot11_race char(2) NOT NULL default '',
  replays_sc2_slot11_details mediumblob NOT NULL,
  replays_sc2_slot11_advanced_details mediumblob NOT NULL,
  replays_sc2_slot12_name varchar(25) NOT NULL default '',
  replays_sc2_slot12_race char(2) NOT NULL default '',
  replays_sc2_slot12_details mediumblob NOT NULL,
  replays_sc2_slot12_advanced_details mediumblob NOT NULL,
  replays_sc2_chat_log mediumblob NOT NULL,
  PRIMARY KEY (replays_sc2_id)
){engine};

INSERT INTO {pre}_options (options_mod, options_name, options_value) VALUES ('replays_sc2', 'games_ids', '');
INSERT INTO {pre}_options (options_mod, options_name, options_value) VALUES ('replays_sc2', 'apmdiagram', '1');
INSERT INTO {pre}_options (options_mod, options_name, options_value) VALUES ('replays_sc2', 'apmx', '400');
INSERT INTO {pre}_options (options_mod, options_name, options_value) VALUES ('replays_sc2', 'apmy', '300');
INSERT INTO {pre}_options (options_mod, options_name, options_value) VALUES ('replays_sc2', 'overwrite', 'map,version');
INSERT INTO {pre}_options (options_mod, options_name, options_value) VALUES ('replays_sc2', 'bgcolor', '000000');
INSERT INTO {pre}_options (options_mod, options_name, options_value) VALUES ('replays_sc2', 'labelcolor', 'FFFFFF');
INSERT INTO {pre}_options (options_mod, options_name, options_value) VALUES ('replays_sc2', 'gridcolor', '404040');
